### ISSUE TITLE
TypeError: this.fetch is not a function

### ISSUE THREAD

**Issue by themustafaomar** [probot/smee-client#285]
Hi,

Firstly, thanks for working on this great service, really helpful.

I'm encountering an error when receiving a payload. It's throwing the following error.

![image](https://github.com/probot/smee-client/assets/46113191/9f8a00fa-5b44-45e4-b7ed-1c3661b62eca)

Oddly, it worked fine on another machine yesterday, any ideas on what might be causing this?

**Comment by wolfy1339** [comment]
What version of Node? What version of `smee-client`?

**Comment by themustafaomar** [comment]
`Node` v16.20.2
`smee-client` v2.0.0

**Comment by wolfy1339** [comment]
Yeah, that would be the issue. You'll need to upgrade your Node version to at least v18.

I'm not sure why it isn't marked in the `package.json` though.

**Comment by themustafaomar** [comment]
Thank you for the fast response 🎉

**Comment by akrieger** [comment]
I'm using node v20 and still hitting this. Trying to run [probot](https://github.com/electron/trop) on a raspi on ubuntu, smee-client ^2.0.1.
```
cdda@ubuntupi:~/trop$ ./run_trop.sh
yarn run v1.22.22
$ probot run ./lib/index.js
getEnvVar: Fetching env var 'SUPPORTED_BRANCH_PATTERN'
INFO (server): Running Probot v12.3.4 (Node.js: v20.13.1)
INFO (server): Forwarding https://smee.io/XeUQ6rLwFPpW4PXx to http://localhost:3000/
INFO (server): Listening on http://localhost:3000
INFO (server): Connected
ERROR (server): this.fetch is not a function
    TypeError: this.fetch is not a function
        at Client.onmessage (/home/cdda/trop/node_modules/smee-client/index.js:44:41)
        at EventSource.emit (node:events:519:28)
        at EventSource.emit (node:domain:488:12)
        at _emit (/home/cdda/trop/node_modules/eventsource/lib/eventsource.js:287:17)
        at parseEventStreamLine (/home/cdda/trop/node_modules/eventsource/lib/eventsource.js:302:9)
        at IncomingMessage.<anonymous> (/home/cdda/trop/node_modules/eventsource/lib/eventsource.js:259:11)
        at IncomingMessage.emit (node:events:519:28)
        at IncomingMessage.emit (node:domain:488:12)
        at addChunk (node:internal/streams/readable:559:12)
        at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
```
