### ISSUE TITLE
Beta branch - Not supporting special chars in received payload

### ISSUE THREAD

**Issue by Dancho80** [probot/smee-client#319]
in case the payload contains some special char like ®, the client fails with error:

```
TypeError: Cannot convert argument to a ByteString because the character at index 10117 has a value of 8482 which is greater than 255.
at Client.fetch (/smee-client/node_modules/undici/index.js:112:13)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Client.onmessage (file:///smee-client/index.js:52:30)
```

**Comment by wolfy1339** [comment]
Can you try changing line 82 so it looks like this
```ts
    headers["content-type"] = "application/json; charset=utf-8";
```
Are you sending the payload as JSON or urlencoded?

**Comment by Dancho80** [comment]
same error
my use case: sending Webhooks from GitHub, Content Type = application/json

**Comment by boegel** [comment]
Same problem also happens when event data (like PR comments) include emojis...
